version: '2'
services:
  worker:
    build: .
    command: go run cmd/crawl_worker/crawl_worker.go -nsqd nsqd:4150 -redis redis://redis:6379
    depends_on:
      - nsqd
      - redis 
  redis:
    ports:
      - "6379:6379"
    image: redis:alpine  
  nsqlookupd:
    image: nsqio/nsq
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd
  nsqd:
    image: nsqio/nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    depends_on:
      - nsqlookupd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
  nsqadmin:
    image: nsqio/nsq
    ports:
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd