version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd
    ports: 
      - "2379:2379"
    command: >
      -listen-client-urls http://0.0.0.0:2379
      -advertise-client-urls http://etcd:2379

  nsqlookupd:
    image: nsqio/nsq
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd

  nsqd:
    image: nsqio/nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    depends_on:
      - nsqlookupd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160

  nsqadmin:
    image: nsqio/nsq
    ports:
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd